/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintProjeto;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.PopupMenu;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
import java.awt.Point;
import static java.lang.Integer.parseInt;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ReSid5
 */

public class TelaInicial extends javax.swing.JFrame {

    ArrayList<Figura> figura = new ArrayList<Figura>();
    Serializador s = new Serializador();
    Deserializador d = new Deserializador();
    Color CorGlobal = new Color(0);
   
    //JFrame F = new JFrame();
    String coordXCirculo;
    String raioCirculo;
    String coordYCirculo;

    String coordXRetangulo;
    String coordYRetangulo;
    String alturaRetangulo;
    String larguraRetangulo;

    String coordXPrimLinha;
    String coordYPrimLinha;
    String coordXSegLinha;
    String coordYSegLinha;


    /**
     * Creates new form tel
     */
    public TelaInicial() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameLinha = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        posicaoXPrimLinha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        posicaoYPrimLinha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        posicaoXSegLinha = new javax.swing.JTextField();
        posicaoYSegLinha = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        botaoCriarLinha = new javax.swing.JButton();
        frameRetangulo = new javax.swing.JInternalFrame();
        labLargura = new javax.swing.JLabel();
        labAltura = new javax.swing.JLabel();
        larguraRectTxtField = new javax.swing.JTextField();
        alturaRectTxtField = new javax.swing.JTextField();
        jLabelXRect = new javax.swing.JLabel();
        posicaoRetanguloX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        posicaoRetanguloY = new javax.swing.JTextField();
        botaoCriarRetangulo = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        frameCirculo = new javax.swing.JInternalFrame();
        labRaio = new javax.swing.JLabel();
        raioCirc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        posicaoCirculoX = new javax.swing.JTextField();
        posicaoCirculoY = new javax.swing.JTextField();
        botaoCriarCirculo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jColorChooser1 = new javax.swing.JColorChooser();
        papel = new desenhaC();
        jSeparator4 = new javax.swing.JSeparator();
        painelInformacao = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRecarregar = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCirculo = new javax.swing.JMenuItem();
        jMenuItemRetangulo = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuCor = new javax.swing.JMenu();

        frameLinha.setVisible(true);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Primeiro ponto ");

        jLabel5.setText("Coordenada X:");

        posicaoXPrimLinha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoXPrimLinhaFocusLost(evt);
            }
        });

        jLabel6.setText("Coordenada Y:");

        posicaoYPrimLinha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoYPrimLinhaFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("Segundo Ponto");

        jLabel8.setText("Coordenada X:");

        jLabel9.setText("Coordenada Y:");

        posicaoXSegLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoXSegLinhaActionPerformed(evt);
            }
        });
        posicaoXSegLinha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoXSegLinhaFocusLost(evt);
            }
        });

        posicaoYSegLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoYSegLinhaActionPerformed(evt);
            }
        });
        posicaoYSegLinha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoYSegLinhaFocusLost(evt);
            }
        });

        botaoCriarLinha.setText("Adicionar");
        botaoCriarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarLinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameLinhaLayout = new javax.swing.GroupLayout(frameLinha.getContentPane());
        frameLinha.getContentPane().setLayout(frameLinhaLayout);
        frameLinhaLayout.setHorizontalGroup(
            frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLinhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLinhaLayout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(134, 134, 134))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLinhaLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
            .addGroup(frameLinhaLayout.createSequentialGroup()
                .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameLinhaLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(botaoCriarLinha))
                    .addGroup(frameLinhaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameLinhaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicaoXSegLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frameLinhaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicaoYSegLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(frameLinhaLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frameLinhaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicaoXPrimLinha))
                            .addGroup(frameLinhaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicaoYPrimLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frameLinhaLayout.setVerticalGroup(
            frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLinhaLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(posicaoXPrimLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(posicaoYPrimLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(posicaoXSegLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(posicaoYSegLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCriarLinha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameRetangulo.setTitle("Criar Retangulo");
        frameRetangulo.setPreferredSize(new java.awt.Dimension(265, 250));
        frameRetangulo.setVisible(true);

        labLargura.setText("Largura: ");

        labAltura.setText("Altura: ");

        larguraRectTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larguraRectTxtFieldActionPerformed(evt);
            }
        });
        larguraRectTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                larguraRectTxtFieldFocusLost(evt);
            }
        });

        alturaRectTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaRectTxtFieldActionPerformed(evt);
            }
        });
        alturaRectTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alturaRectTxtFieldFocusLost(evt);
            }
        });

        jLabelXRect.setText("Posição x:");

        posicaoRetanguloX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoRetanguloXActionPerformed(evt);
            }
        });
        posicaoRetanguloX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoRetanguloXFocusLost(evt);
            }
        });

        jLabel3.setText("Posição y:");

        posicaoRetanguloY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoRetanguloYActionPerformed(evt);
            }
        });
        posicaoRetanguloY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoRetanguloYFocusLost(evt);
            }
        });

        botaoCriarRetangulo.setText("Adicionar");
        botaoCriarRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarRetanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameRetanguloLayout = new javax.swing.GroupLayout(frameRetangulo.getContentPane());
        frameRetangulo.getContentPane().setLayout(frameRetanguloLayout);
        frameRetanguloLayout.setHorizontalGroup(
            frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameRetanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameRetanguloLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(labAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameRetanguloLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(labLargura)))
                    .addComponent(jLabelXRect)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posicaoRetanguloY)
                    .addComponent(posicaoRetanguloX)
                    .addComponent(alturaRectTxtField)
                    .addComponent(larguraRectTxtField))
                .addGap(61, 61, 61))
            .addGroup(frameRetanguloLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(botaoCriarRetangulo)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(jSeparator6)
        );
        frameRetanguloLayout.setVerticalGroup(
            frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameRetanguloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAltura)
                    .addComponent(alturaRectTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(larguraRectTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXRect)
                    .addComponent(posicaoRetanguloX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(posicaoRetanguloY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCriarRetangulo)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        frameCirculo.setTitle("Criar Circulo");
        frameCirculo.setMinimumSize(new java.awt.Dimension(62, 45));
        frameCirculo.setVisible(true);

        labRaio.setText("Raio: ");

        raioCirc.setToolTipText("raio");
        raioCirc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raioCircActionPerformed(evt);
            }
        });
        raioCirc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                raioCircFocusLost(evt);
            }
        });

        jLabel1.setText("Posição x:");

        jLabel2.setText("Posição y:");

        posicaoCirculoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoCirculoXActionPerformed(evt);
            }
        });
        posicaoCirculoX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoCirculoXFocusLost(evt);
            }
        });

        posicaoCirculoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoCirculoYActionPerformed(evt);
            }
        });
        posicaoCirculoY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                posicaoCirculoYFocusLost(evt);
            }
        });

        botaoCriarCirculo.setText("Adicionar");
        botaoCriarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameCirculoLayout = new javax.swing.GroupLayout(frameCirculo.getContentPane());
        frameCirculo.getContentPane().setLayout(frameCirculoLayout);
        frameCirculoLayout.setHorizontalGroup(
            frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(frameCirculoLayout.createSequentialGroup()
                .addGroup(frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameCirculoLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(botaoCriarCirculo))
                    .addGroup(frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(frameCirculoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(posicaoCirculoY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameCirculoLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(labRaio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(raioCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(frameCirculoLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(posicaoCirculoX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        frameCirculoLayout.setVerticalGroup(
            frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCirculoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(raioCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(posicaoCirculoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicaoCirculoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCriarCirculo)
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BruTon Editor - Paint");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(720, 453));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        papel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout papelLayout = new javax.swing.GroupLayout(papel);
        papel.setLayout(papelLayout);
        papelLayout.setHorizontalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        papelLayout.setVerticalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(papelLayout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 443, Short.MAX_VALUE))
        );

        jLabel10.setText("Bem Vindo ao Editor-Paint ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("BruTon");

        javax.swing.GroupLayout painelInformacaoLayout = new javax.swing.GroupLayout(painelInformacao);
        painelInformacao.setLayout(painelInformacaoLayout);
        painelInformacaoLayout.setHorizontalGroup(
            painelInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacaoLayout.createSequentialGroup()
                .addGroup(painelInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInformacaoLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel10))
                    .addGroup(painelInformacaoLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel11)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        painelInformacaoLayout.setVerticalGroup(
            painelInformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        menuRecarregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\DULCI\\Dropbox\\Mini Projeto Tpe2\\versões do projeto\\ProjetoTPE versão 7.1 (com menu cores)\\src\\paintProjeto\\inconRecarregar.png")); // NOI18N
        menuRecarregar.setText("Recarregar");
        menuRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecarregarActionPerformed(evt);
            }
        });
        jMenu1.add(menuRecarregar);

        menuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintProjeto/iconSalvar.jpg"))); // NOI18N
        menuSalvar.setText("Salvar");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalvar);

        menuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintProjeto/iconDelete.png"))); // NOI18N
        menuExcluir.setText("Excluir");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        jMenu1.add(menuExcluir);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Adicionar");

        jMenuItemCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintProjeto/iconCirc.gif"))); // NOI18N
        jMenuItemCirculo.setText("Circulo");
        jMenuItemCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCirculoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCirculo);

        jMenuItemRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintProjeto/inconRetan.gif"))); // NOI18N
        jMenuItemRetangulo.setText("Retangulo");
        jMenuItemRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRetanguloActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRetangulo);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintProjeto/iconLinha.png"))); // NOI18N
        jMenuItem5.setText("Linha");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        MenuCor.setText("Cor");
        MenuCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCorMouseClicked(evt);
            }
        });
        MenuCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCorActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuCor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(papel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(papel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Color getGlobalCor(){
        return CorGlobal;
    }
    
    private void menuRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecarregarActionPerformed
        try {
            JFileChooser seletorArquivos =new JFileChooser();
            int i;
           
            figura = null;
            figura = (ArrayList<Figura>) d.deserializar("ArquivoFiguras.txt");
            for(i=0; i< figura.size(); i++){
                //System.out.println("ArrayList: " + f.getNome() + " - " + f.getCor());
                if(figura.get(i) instanceof Circulo){
                    Circulo c = (Circulo)figura.get(i);
                ((desenhaC)this.papel).desenhoCirculo( c.getPosicao(), c.getRaio(),c.getCor());
                }
                if(figura.get(i) instanceof Retangulo){
                    Retangulo r = (Retangulo)figura.get(i);
                ((desenhaC)this.papel).desenhoRetangulo( r.getPosicao(), r.getAltura(), r.getLargura(), r.getCor());
                }
                if(figura.get(i) instanceof Linha){
                    Linha l = (Linha)figura.get(i);
                ((desenhaC)this.papel).desenhoLinha( l.getPosicao(), l.getSegPonto(),l.getCor());
                }
                
                
            }
        } catch (Exception ex) {
            System.err.println("Falha ao  deserializar! - " +
                               ex.toString());
        }
    }//GEN-LAST:event_menuRecarregarActionPerformed

    private void jMenuItemCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCirculoActionPerformed
        // evento quando seleciona-se Circulo:
        JFrame F = new JFrame();
        F.setVisible(true);
        F.setSize(270, 270);
        F.setResizable(false);
	F.setLocationRelativeTo(null);
        
        //Algumas configurações gerais  
        frameCirculo.setClosable(true);//Se o frame vai poder ser fechado pelo botão fechar   
        frameCirculo.setIconifiable(true);//Se o frame vai poder ser minimizado.  
        frameCirculo.setResizable(true);//Pemite editar o tamanho.  
        frameCirculo.setVisible(true);
        F.add(frameCirculo);
        //Papel.add(frameCirculo, BorderLayout.CENTER);

    //Torna o seu painel interno visível  
        frameCirculo.setSize(450, 450);
        
        
    }//GEN-LAST:event_jMenuItemCirculoActionPerformed

    private void raioCircActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raioCircActionPerformed
        

    }//GEN-LAST:event_raioCircActionPerformed

    private void jMenuItemRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRetanguloActionPerformed
        //evento quando seleciona-se Retangulo:
        //Algumas configurações gerais  
        JFrame D = new JFrame();
        frameRetangulo.setClosable(true);//Se o frame vai poder ser fechado pelo botão fechar   
        frameRetangulo.setIconifiable(true);//Se o frame vai poder ser minimizado.  
        frameRetangulo.setResizable(true);//Pemite editar o tamanho.  
        D.add(frameRetangulo);
        D.setSize(265,285);
        D.setVisible(true);
        D.setResizable(false);
	D.setLocationRelativeTo(null);
      // this.add(frameRetangulo, BorderLayout.CENTER);
        frameRetangulo.setSize(265, 250);
        frameRetangulo.setVisible(true);
    }//GEN-LAST:event_jMenuItemRetanguloActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
   // TODO add your handling code here:

    }//GEN-LAST:event_formFocusGained

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:   
    }//GEN-LAST:event_formMouseDragged

    private void posicaoCirculoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoCirculoXActionPerformed
       
    }//GEN-LAST:event_posicaoCirculoXActionPerformed

    private void posicaoCirculoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoCirculoYActionPerformed
        // TODO add your handling code here:
        //String valor;
        //valor= posicaoCirculoY.getText();
        //System.out.println(valor);
        coordYCirculo = posicaoCirculoY.getText();
        System.out.println("estou pegando um Y");
        //Ponto p = new Ponto();
        //figsCirculo.add(new Circulo());
        //posicao.setY(parseInt(valor)) ;
        //System.out.println("vc setou a porra da posicao Y");
    }//GEN-LAST:event_posicaoCirculoYActionPerformed

    private void botaoCriarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarCirculoActionPerformed
        
    try{    
        String valorx, valory, valorR;
        int raio; 
        
        Ponto posicao = new Ponto(0, 0);
        
        valorR = raioCirculo;
        valory = coordYCirculo;
        valorx = coordXCirculo;
        
        raio = Integer.parseInt(valorR);
        posicao.setX(Integer.parseInt(valorx));
        posicao.setY(Integer.parseInt(valory));
        
        figura.add(new Circulo(posicao, raio,CorGlobal));
        System.out.println("numero de figuras " + figura.size());
       
        ((desenhaC)this.papel).desenhoCirculo(posicao, raio,CorGlobal);
            if(raio <= 0 || posicao.getX()< 0 ||  posicao.getX() < 0 ){
                throw new IllegalArgumentException("") ;
            }
            if(posicao.getX() > papel.getWidth() || posicao.getY() > papel.getHeight()|| raio+posicao.getX() > papel.getWidth() || raio+posicao.getY()> papel.getHeight() ){
                throw new ForaAreaException();
            }
    }
    
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Valores de formulario devem ser inteiros");
    }
     catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Digite valores positivos ");
        }   
     catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada fora da area de desenho! ");
        }  
    }//GEN-LAST:event_botaoCriarCirculoActionPerformed
   
    private void posicaoCirculoYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoCirculoYFocusLost
        // TODO add your handling code here:
        
        try{
        int tempx;
        coordYCirculo = posicaoCirculoY.getText();
        tempx = Integer.parseInt(coordYCirculo);
         if(tempx < 0){
        throw new IllegalArgumentException("") ;
        }
         if(tempx > papel.getHeight()){
        throw new ForaAreaException() ;
        }
        
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada Y");
        }
        catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Digite valores positivos na coordenada Y! ");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada Y fora da area de desenho! ");
        }
    }//GEN-LAST:event_posicaoCirculoYFocusLost

    private void posicaoCirculoXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoCirculoXFocusLost
        // TODO add your handling code here:
        
        try{
        int tempx;
        coordXCirculo = posicaoCirculoX.getText();
        tempx = Integer.parseInt(coordXCirculo);
        if(tempx < 0){
        throw new IllegalArgumentException() ;
        }
        if(tempx > papel.getWidth()){
            
        throw new ForaAreaException() ; 
        }
        }catch(NumberFormatException e){
            
            JOptionPane.showMessageDialog(null, "Digite valores númericos na coordenada X! ");
        }
        
        catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Digite valores positivos na coordenada X! ");
        } catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada X fora da area de desenho! ");
        }


    }//GEN-LAST:event_posicaoCirculoXFocusLost

    private void raioCircFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_raioCircFocusLost
        // TODO add your handling code here:
        
        
        try{
        int tempx;
        raioCirculo = raioCirc.getText();
        tempx = Integer.parseInt(raioCirculo);
        //System.out.println("estou pegando um raio,  " + raioCirculo );
        if(tempx <= 0){
        throw new IllegalArgumentException();
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para o Raio");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null, "Digite valores positivos para o raio ");
        }
    }//GEN-LAST:event_raioCircFocusLost

    private void posicaoRetanguloXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoRetanguloXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoRetanguloXActionPerformed

    private void posicaoRetanguloYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoRetanguloYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoRetanguloYActionPerformed

    private void alturaRectTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaRectTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaRectTxtFieldActionPerformed

    private void alturaRectTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alturaRectTxtFieldFocusLost
        // TODO add your handling code here:
        try{
        int tempx;
        alturaRetangulo = alturaRectTxtField.getText();
        tempx = Integer.parseInt(alturaRetangulo);
        //System.out.println("estou pegando um raio,  " + raioCirculo );
        if(tempx <= 0){
        throw new IllegalArgumentException();
        }
        if(tempx > papel.getHeight()){throw new ForaAreaException();}
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Altura");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Altura");
        } 
        catch(ForaAreaException e){
        JOptionPane.showMessageDialog(null,"Valor fora da area de desenho");
        } 
       
    }//GEN-LAST:event_alturaRectTxtFieldFocusLost

    private void larguraRectTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larguraRectTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_larguraRectTxtFieldActionPerformed

    private void larguraRectTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_larguraRectTxtFieldFocusLost
        // TODO add your handling code here:
        
        try{
            int tempx;
            larguraRetangulo = larguraRectTxtField.getText();
            tempx = Integer.parseInt(larguraRetangulo);
                if(tempx <= 0){
                throw new IllegalArgumentException();
                }
                if(tempx > papel.getWidth()){throw new ForaAreaException();}
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para largura");
        }
         catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para largura");
        } 
        catch(ForaAreaException e){
        JOptionPane.showMessageDialog(null,"Valor fora da area de desenho");
        } 
    }//GEN-LAST:event_larguraRectTxtFieldFocusLost

    private void posicaoRetanguloXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoRetanguloXFocusLost
        // TODO add your handling code here:
        try{
            int tempx;
            coordXRetangulo = posicaoRetanguloX.getText();
            tempx = Integer.parseInt(coordXRetangulo);
            if(tempx < 0 ){
            throw new IllegalArgumentException();
            }
             if(tempx > papel.getWidth()){
            throw new ForaAreaException();
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada X");
        }
          catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Coordenada X");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada X fora da area de desenho! ");
        } 
    }//GEN-LAST:event_posicaoRetanguloXFocusLost

    private void posicaoRetanguloYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoRetanguloYFocusLost
        // TODO add your handling code here:
        
        try{
            coordYRetangulo = posicaoRetanguloY.getText();
            int tempx;
            tempx = Integer.parseInt(coordYRetangulo);
            if(tempx < 0){
            throw new IllegalArgumentException();
            }
            if(tempx > papel.getHeight()) {throw new ForaAreaException();}
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada Y");
        }
         catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Coordenada Y");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada Y fora da area de desenho! ");
        }
       
    }//GEN-LAST:event_posicaoRetanguloYFocusLost

    private void botaoCriarRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarRetanguloActionPerformed
        // TODO add your handling code here:
        //System.out.println("vc clicou a porra do botão"); 
        try{
        String valorx, valory, valorL, valorA;
        int altura, largura;
        Ponto posicao = new Ponto(0, 0);
        valorA = alturaRetangulo;
        valorL = larguraRetangulo;
        valory = coordYRetangulo;
        valorx = coordXRetangulo;

        altura = Integer.parseInt(valorA);
        largura = Integer.parseInt(valorL);
        //System.out.println("largura e altura inteiros"); 
        posicao.setX(Integer.parseInt(valorx));
        posicao.setY(Integer.parseInt(valory));
        //System.out.println(" TUDO deu certo");
        figura.add(new Retangulo(posicao, altura, largura, CorGlobal));
        System.out.println("numero de figuras " + figura.size());
       
       ((desenhaC)this.papel).desenhoRetangulo(posicao, altura,largura,CorGlobal);
       
       if(largura <= 0 || altura <=0 || posicao.getX() <0 || posicao.getX() <0 ){
       throw new IllegalArgumentException();
       }
       if(posicao.getX() >papel.getWidth() || posicao.getY() >papel.getHeight()|| largura + posicao.getX() > papel.getWidth() || altura + posicao.getY() > papel.getHeight() ){throw new ForaAreaException();}
    }//GEN-LAST:event_botaoCriarRetanguloActionPerformed
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Digite valores numéricos ");
    }
    catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos");
        }
    catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenadas  fora da area de desenho! ");
        }    
    }
    
    private void posicaoXSegLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoXSegLinhaActionPerformed
        
    }//GEN-LAST:event_posicaoXSegLinhaActionPerformed

    private void posicaoYSegLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoYSegLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoYSegLinhaActionPerformed

    private void posicaoXPrimLinhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoXPrimLinhaFocusLost
        // TODO add your handling code here
        
         try{
        int tempx;
        coordXPrimLinha = posicaoXPrimLinha.getText();
        tempx = Integer.parseInt(coordXPrimLinha);
        if(tempx < 0){throw new IllegalArgumentException();}
        if(tempx > papel.getWidth()){ throw new ForaAreaException();}
         }
         
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada X");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Coordenada X da posição inicial");
        } 
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada X fora da area de desenho! ");
        }     
    }//GEN-LAST:event_posicaoXPrimLinhaFocusLost

    private void posicaoYPrimLinhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoYPrimLinhaFocusLost
        // TODO add your handling code here:
        
        try{
        int tempx;
        coordYPrimLinha = posicaoYPrimLinha.getText();
        tempx = Integer.parseInt(coordYPrimLinha);
        if(tempx < 0){throw new IllegalArgumentException();}
        if(tempx > papel.getHeight()){ throw new ForaAreaException();}
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada Y");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Coordenada Y da posição inicial");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada Y fora da area de desenho! ");
        } 

    }//GEN-LAST:event_posicaoYPrimLinhaFocusLost

    private void posicaoXSegLinhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoXSegLinhaFocusLost
        // TODO add your handling code here:
        
        try{
        int tempx;
        coordXSegLinha = posicaoXSegLinha.getText();
        tempx = Integer.parseInt(coordXSegLinha);
        if(tempx < 0){throw new IllegalArgumentException();}
        if(tempx > papel.getWidth()){throw new ForaAreaException(); }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada X");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Coordenada X da segunda linha");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada X fora da area de desenho! ");
        } 

    }//GEN-LAST:event_posicaoXSegLinhaFocusLost

    private void posicaoYSegLinhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posicaoYSegLinhaFocusLost
        // TODO add your handling code here:
        
        try{
        int tempx;
        coordYSegLinha = posicaoYSegLinha.getText();
        tempx = Integer.parseInt(coordYSegLinha);
        if(tempx < 0){throw new IllegalArgumentException();}
        if(tempx > papel.getHeight()){throw new ForaAreaException();}
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite valores numéricos para Coordenada Y");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos para Coordenada Y da segunda linha");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenada Y fora da area de desenho! ");
        } 
    }//GEN-LAST:event_posicaoYSegLinhaFocusLost

    private void botaoCriarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarLinhaActionPerformed
        // TODO add your handling code here:
        //System.out.println("vc clicou a porra do botão da linha"); 
        try{
        String valorx1, valory1, valorx2, valory2;
        Ponto posicao1 = new Ponto(0, 0);
        Ponto posicao2 = new Ponto(0, 0);
        valorx1 = coordXPrimLinha;
        valory1 = coordYPrimLinha;
        valorx2 = coordXSegLinha;
        valory2 = coordYSegLinha;

        posicao1.setX(Integer.parseInt(valorx1));
        posicao1.setY(Integer.parseInt(valory1));
        posicao2.setX(Integer.parseInt(valorx2));
        posicao2.setY(Integer.parseInt(valory2));
        
        
        figura.add(new Linha(posicao1, posicao2,CorGlobal));
        System.out.println("numero de figuras " + figura.size());
        ((desenhaC)this.papel).desenhoLinha(posicao1, posicao2,CorGlobal);
            if(posicao1.getX() < 0|| posicao1.getY() <0 || posicao2.getX() < 0 || posicao2.getY() < 0 ){
            throw new IllegalArgumentException();
            }
            if(posicao1.getX() > papel.getWidth()|| posicao1.getY() >papel.getHeight() || posicao2.getX() > papel.getWidth() || posicao2.getY() > papel.getHeight()){
            throw new ForaAreaException();
            }
        }
        catch(NumberFormatException e ){
           JOptionPane.showMessageDialog(null,"Digite valores numéricos");
        }
        catch(IllegalArgumentException e){
        JOptionPane.showMessageDialog(null,"Digite valores positivos ");
        }
        catch (ForaAreaException ex) {
            JOptionPane.showMessageDialog(null, "Coordenadas      fora da area de desenho! ");
        } 
    }//GEN-LAST:event_botaoCriarLinhaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here
        //evento quando seleciona-se Linha:
        //Algumas configurações gerais  
        JFrame L = new JFrame();
        L.setSize(399, 375);
        L.setVisible(true);
        L.setResizable(false);
	L.setLocationRelativeTo(null);
        frameLinha.setClosable(true);//Se o frame vai poder ser fechado pelo botão fechar   
       frameLinha.setIconifiable(true);//Se o frame vai poder ser minimizado.  
        frameLinha.setResizable(false);//Pemite editar o tamanho.  
        L.add(frameLinha);
        //papel.add(frameLinha, BorderLayout.CENTER);
       // this.add(frameLinha, BorderLayout.CENTER);
        frameLinha.setSize(399, 375);
        frameLinha.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        // TODO add your handling code here:
        try {
            s.serializar("ArquivoFiguras.txt", figura);
            JOptionPane.showMessageDialog(null, "Arquivo salvo");
           
           
            
        } catch (Exception ex) {
            System.err.println("Falha ao serializar ou deserializar! - " +
                               ex.toString());
        }
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void MenuCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MenuCorActionPerformed

    private void MenuCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCorMouseClicked
        // TODO add your handling code here:
        CorGlobal = JColorChooser.showDialog(this,"Selecione a Cor", CorGlobal);
        ((desenhaC)this.papel).definirCor(CorGlobal);
    }//GEN-LAST:event_MenuCorMouseClicked

    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        // TODO add your handling code here:
        //figura.remove(figura);
        CorGlobal = new Color(255) ;
        ((desenhaC)this.papel).figuras.clear();
        figura.removeAll(figura);
        repaint();
        
    }//GEN-LAST:event_menuExcluirActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCor;
    private javax.swing.JTextField alturaRectTxtField;
    private javax.swing.JButton botaoCriarCirculo;
    private javax.swing.JButton botaoCriarLinha;
    private javax.swing.JButton botaoCriarRetangulo;
    private javax.swing.JInternalFrame frameCirculo;
    private javax.swing.JInternalFrame frameLinha;
    private javax.swing.JInternalFrame frameRetangulo;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelXRect;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemCirculo;
    private javax.swing.JMenuItem jMenuItemRetangulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labAltura;
    private javax.swing.JLabel labLargura;
    private javax.swing.JLabel labRaio;
    private javax.swing.JTextField larguraRectTxtField;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JMenuItem menuRecarregar;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JPanel painelInformacao;
    private javax.swing.JPanel papel;
    private javax.swing.JTextField posicaoCirculoX;
    private javax.swing.JTextField posicaoCirculoY;
    private javax.swing.JTextField posicaoRetanguloX;
    private javax.swing.JTextField posicaoRetanguloY;
    private javax.swing.JTextField posicaoXPrimLinha;
    private javax.swing.JTextField posicaoXSegLinha;
    private javax.swing.JTextField posicaoYPrimLinha;
    private javax.swing.JTextField posicaoYSegLinha;
    private javax.swing.JTextField raioCirc;
    // End of variables declaration//GEN-END:variables

    

}
